### ISSUE TITLE
Golang build broken: parameterToString undefined

### ISSUE THREAD

**Issue by mattolson** [mxenabled/openapi#131]
Cross posting here in case there is more visibility on this repo. It seems that the golang build is broken.

https://github.com/mxenabled/mx-platform-go/issues/47

**Comment by JigarJoshi04** [comment]
I think we need to close this, as the link you mentioned in issue has a PR linked to it.
Please refer https://github.com/mxenabled/mx-platform-go/issues/47

**Comment by mattolson** [comment]
@JigarJoshi04 That's fine. Can you try to get some attention on that PR?

**Comment by mattolson** [comment]
Fixed by https://github.com/mxenabled/mx-platform-go/pull/49
